gamereview/gamereview/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf import settings


urlpatterns = [
    path('reviews/', include('reviews.urls')),
    path('', RedirectView.as_view(url='reviews/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gamereview/reviews/urls.py
from django.urls import path, include
from django.views import generic

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('publishers/', views.PublisherView.as_view(), name='publishers'),
    path('publisher/<int:publisher_id>',
         views.publisher, name='publisher'),
    path('games/', views.GameListView.as_view(), name='games'),
    path('game/<int:pk>', views.GameDetailView.as_view(), name='game'),
    path('i18n/', include('django.conf.urls.i18n')),
    # api
    path('game-reviews', views.ReviewListApi.as_view())
]

gamereview/reviews/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.core.validators import MaxValueValidator, MinValueValidator


class Genre(models.Model):
    name = models.CharField('TName', max_length=200,
                            help_text='Select or create game genre (FPS)')

    def __str__(self):
        return self.name


class Game(models.Model):
    """Modelis reprezentuoja žaidimą"""
    title = models.CharField('Name', max_length=200)
    publisher = models.ForeignKey(
        'Publisher', on_delete=models.SET_NULL, null=True, related_name='games')
    summary = models.TextField(
        _('Summary'), max_length=1000, help_text='Game description')
    genre = models.ManyToManyField(
        Genre, help_text='Select genres for games')
    cover = models.ImageField('Cover', upload_to='covers', null=True)

    def __str__(self):
        return f'{self.title}'


class Publisher(models.Model):
    """Model representing a publisher."""
    name = models.CharField('Name', max_length=100)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.name}'


class GameReview(models.Model):
    game = models.ForeignKey(
        Game, on_delete=models.SET_NULL, null=True, blank=True)
    reviewer = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveIntegerField('Rating', default=50, validators=[
        MinValueValidator(0), MaxValueValidator(100)])
    content = models.TextField('Review Content', max_length=2000)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.game.title}'

gamereview/reviews/forms.py
from .models import GameReview
from django import forms


class GameReviewForm(forms.ModelForm):
    class Meta:
        model = GameReview
        fields = ('reviewer', 'game', 'content', 'rating')
        widgets = {'game': forms.HiddenInput(
        ), 'reviewer': forms.HiddenInput()}

gamereview/reviews/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .forms import GameReviewForm
from .models import GameReview, Publisher, Game
from django.views import generic
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.views.generic.edit import FormMixin
from django.db.models import Max
# papildomai importuojame permissions!
from rest_framework import generics, permissions
from .serializers import GameReviewSerializer


def index(request):

    return render(request, "index.html")


@csrf_protect
def register(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(
                    request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'registration/register.html')


def new_view(request):
    return render(request, 'registration/register.html')

class PublisherView(generic.ListView):
    model = Publisher
    template_name = 'publishers.html'
    paginate_by = 3


def publisher(request, publisher_id):
    single_publisher = get_object_or_404(Publisher, pk=publisher_id)
    return render(request, 'publisher.html', {'publisher': single_publisher})


class GameListView(generic.ListView):
    model = Game
    template_name = 'games.html'
    paginate_by = 3


class GameDetailView(FormMixin, generic.DetailView):
    model = Game
    template_name = 'game.html'
    form_class = GameReviewForm

    # nurodome, kur atsidursime komentaro sėkmės atveju.

    def get_success_url(self):
        return reverse('game', kwargs={'pk': self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.game = self.object
        form.instance.reviewer = self.request.user
        form.save()
        return super(GameDetailView, self).form_valid(form)

# API


class ReviewListApi(generics.ListAPIView):
    queryset = GameReview.objects.all()
    serializer_class = GameReviewSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(reviewer=self.request.user)

gamereview/reviews/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">

    {% if title %}
        <title>Review Site - {{ title }}</title>
    {% else %}
        <title>Review Site</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'index' %}">Home</a> 
              <a class="nav-item nav-link" href="{% url 'publishers' %}">Publishers</a> 
              <a class="nav-item nav-link" href="{% url 'games' %}">Games</a> 
            </div>
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link">{{ user.username }}</a> 
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
              </div>
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              {% else %}
              {% endif %}
            </div>
          </div>
        </div>
        <form action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input name="next" type="hidden" value="{{ redirect_to }}"/>
          <select name="language" onchange="this.form.submit()">
            {% load static %}
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% for lang in LANGUAGES %}
            <option style="background-image: url({% static 'img/lt.png' %});" value="{{ lang.0 }}" {% if lang.0 == LANGUAGE_CODE %} selected="selected" {% endif %}>
              {{ lang.1 }}
            </option>
            {% endfor %}
          </select>
        </form>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

gamereview/reviews/templates/game.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="col-md-4">
      <h1>{{ game.title }}</h1>
    <p><strong>Publisher:</strong> <a href="{% url 'publisher' game.publisher.pk %}">{{ game.publisher }}</a></p>
    <p><strong>Genre:</strong> {{ game.genre.all|join:", " }}</p>  
    <p><strong>Description:</strong> {{ game.summary }}</p>
  </br>
  
    <h4>Reviews:</h4>
    {% if game.gamereview.all %}
    {% else %}
      <p>Game doesn't have reviews</p>
    {% endif %}
  </br>
  <hr> 
    <form action="" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Išsaugoti">
    </form>
  </div>
{% endblock %}

gamereview/reviews/templates/games.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container author">
    </br>
    <h5>We have reviewed games:</h5>
    {% if game_list %}
    <div class="row">
      {% for game in game_list %}
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="card mb-4 shadow-sm">
            {% if game.cover %}
              <img src="{{ game.cover.url }}" class="card-img-top" alt="...">
            {% else %}
              <img src="{% static 'img/no-image.png' %}" class="card-img-top">
            {% endif %}
            <div class="card-body">
              <h6 class="card-subtitle mb-2 text-muted">{{ game.publisher }}</h6>
              <p class="card-text"><a href="{% url 'game' game.id %}">{{game.title}} </a></p>
            </div>
          </div>
        </div>
      {% endfor %}
    {% endif %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; pirmas</a>
                <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
            {% endif %}
    
            <span class="current">
                {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a> 
            {% endif %}
        </span>
    </div>       
  </div>
{% endblock %}

gamereview/reviews/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<html>
<head></head>

<body>
    <h1>{% trans "Welcome to game reviews" %}</h1>
    {% if review %}
    <h4>{% trans "Best rated review:" %} {{review.game.title}}</h4>
        <div class="col-md-4 d-flex align-items-stretch">
          <div class="card mb-4 shadow-sm">
            {% if review.game.cover %}
              <img src="{{ review.game.cover.url }}" class="card-img-top" alt="...">
            {% else %}
              <img src="{% static 'img/no-image.png' %}" class="card-img-top">
            {% endif %}
            <strong>{{ review.reviewer }}</strong>, <em>{{ review.date_created}}</em>
            <p>{{ review.content }}</p>
            <h5>{{ review.rating }} / 100</h5>
        {% else %}
          <p>There are no reviews</p>
        {% endif %}
          </div>
        </div>   
</body>

</html>

{% endblock content %}

gamereview/reviews/templates/publisher.html
{% extends "base.html" %}

{% block content %}
    <div class="container author">
    <h4>{{ publisher.name }}</h4>
    <hr/>
    </hr>
    </br>
    <h5>We have reviewed these publisher {{ publisher.name }} games:</h5>
    {% for game in publisher.games.all %}
       <li><a href="http://127.0.0.1:8000/reviews/game/{{game.id}}">{{ game.title }}</a></li>  
    {% endfor %}
    </div>
{% endblock %}

gamereview/reviews/templates/publishers.html
{% extends "base.html" %}

{% block content %}
    <div class="container author">
        </br>
        <h5>We have reviewed games released from these publishers:</h5>
        {% for publisher in publisher_list %}
            <li><a href="{% url 'publisher' publisher.id %}">{{publisher.name}} </a></li>
        {% endfor %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; pirmas</a>
                    <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
                {% endif %}
        
                <span class="current">
                    {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a> 
                {% endif %}
            </span>
        </div>    
    </div>
{% endblock %}